#!/usr/bin/env bash

cp_file=transform-cp
rm ./$cp_file

echo '#!/usr/bin/env bash' >> $cp_file
echo 'source ./cp' >> $cp_file

array_file=(
    ./bootstrap
    ./Shadowsocks/init
)
for FILE in ${array_file[@]}
do
    cat $FILE | grep "cp " | sed 's/cp/mcp/' >> $cp_file
done

echo 'echo Done.' >> $cp_file

chmod +x ./$cp_file

./$cp_file